### PR TITLE
add and change Spec

### PR DESCRIPTION
**Pull request by amicavi**
Add and change the README file

### CODE REVIEW

**Comment by amicavi** [comment]
YES!!!

Can I erase the branch?

2015-11-25 11:32 GMT-06:00 Aaron Gonzalez notifications@github.com:

**Comment by SkeloGH** [comment]
as long as you don't mess with master/staging/develop it's ok

**Comment by SkeloGH** [comment]
wait, no, don't delete it, we'll keep it or the record

**Comment by amicavi** [comment]
Tnx! 
I will search for series. 
this is exciting, my first merge! :+1:

**Pull request merged**
